version: '3.9'
services:

    uas:
        #image: whosgonna/voip_patrol
        build: 
            context: .
            dockerfile: ./Dockerfile
        ports: 
            - 5060:5060/udp
        volumes: 
            - ./uas:/uas
        entrypoint: /git/voip_patrol/voip_patrol --conf /uas/basic_server.xml --port 5060 --log-level-console 10
        #tty: true

    uac:
        #image: whosgonna/voip_patrol
        build: 
            context: .
        volumes: 
            - ./uac:/uac
        entrypoint: sh
        tty: true
